#!/bin/bash

CONFIG="${1}"

if [ -z ${CONFIG} ]; then
	if [ -e $HOME/.config/rbackup/config ]; then
		CONFIG="$HOME/.config/rbackup/config"
	else
		exit 1
	fi
fi

source ${CONFIG}

if [ ! -z ${REMOTE} ]; then
	RSYNC_REMOTE="${REMOTE}:"
fi

OPT="-aPh"

rsync --link-dest=${LAST} ${OPT} ${SRC} ${RSYNC_REMOTE}${DEST}${NAME}

if [ -z $REMOTE ]; then
	rm ${LAST}; ln -sf ${DEST}${NAME} ${LAST}
else
	ssh $REMOTE "rm ${LAST}; ln -sf ${DEST}${NAME} ${LAST}"
fi
